default:
  outputs:
    dev:
      account: rpbypne-hl75678
      database: DBT_DEV_DB
      password: dbtuser
      role: DBT_ROLE
      schema: JM
      threads: 1
      type: snowflake
      user: DBT_USER
      warehouse: DBT_WH
  target: dev
