version: 2

models: 
- name: dim_customer
  description: "testing dim_customer"
  columns:
          - name: customer_id
            description: "The primary key for this table"
            data_tests:
              - unique
              - not_null